Project Development Phase/Sprint 4/Customer Care Registry/registry/routes/cust.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from flask_login import login_required, logout_user
import ibm_db
from .views import conn, customer
import uuid
from datetime import date, datetime
from .views import pass_regex
import re
import hashlib

QUERY_STATUS_OPEN = "OPEN"
QUERY_STATUS_ASSIGNED_AGENT = "AGENT ASSIGNED"
QUERY_STATUS_CLOSE = "CLOSE"

cust = Blueprint("customer", __name__)

@cust.route('/customer/')
@login_required
def profile():
    '''
        Custome can see his/her profile card
    '''
    from .views import customer
        
    if hasattr(customer, 'uuid'):
        return render_template('cust profile.html', customer = customer, id = 0)

    else:
        return redirect(url_for('blue_print.logout'))

@cust.route('/customer/new', methods = ['GET', 'POST'])
@login_required
def new():
    '''
        Customer can create a new ticket 
    '''
    from .views import customer

    if(hasattr(customer, 'uuid')):
        if request.method == 'POST':
            # collecting the query entered by the customer in the textarea
            query = request.form.get('query-box')

            msg = ""
            to_show = False

            if(len(query) == 0):
                msg = "Query cannot be empty!"
                to_show = True

            else:
                # updating the query in the database
                update_query = '''
                    INSERT INTO tickets 
                        (ticket_id, raised_by, raised_on, issue, query_status)
                    VALUES 
                        (?, ?, ?, ?, ?)
                '''

                try:
                    stmt = ibm_db.prepare(conn, update_query)

                    # creating a uuid for the ticket_id
                    ticket_id = str(uuid.uuid4())
                    raised_by = customer.uuid
                    raied_on = datetime.now()

                    ibm_db.bind_param(stmt, 1, ticket_id)
                    ibm_db.bind_param(stmt, 2, raised_by)
                    ibm_db.bind_param(stmt, 3, raied_on)
                    ibm_db.bind_param(stmt, 4, query)
                    ibm_db.bind_param(stmt, 5, QUERY_STATUS_OPEN)

                    ibm_db.execute(stmt)

                    msg = "Ticket created!"
                    to_show = True

                except:
                    msg = "Something went wrong!"
                    to_show = True

            return render_template('cust new ticket.html', id = 1, to_show = to_show, message = msg)

        return render_template('cust new ticket.html', id = 1)

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))

@cust.route('/customer/tickets')
@login_required
def tickets():
    '''
        Fetching all the tickets raised by the customer
    '''
    from .views import customer

    if(hasattr(customer, 'uuid')):
        fetch_query = '''
            SELECT  
                tickets.ticket_id,
                tickets.raised_on,
                tickets.query_status,
                agent.first_name, 
                tickets.issue
            FROM
                tickets
            LEFT JOIN 
                agent ON agent.agent_id = tickets.assigned_to AND
                    tickets.raised_by = ? ORDER BY tickets.raised_on DESC
        '''

        # I am using the LEFT JOIN because
            # the customer should see both the assigned and unassigned tickets
        
        # Left side table - Tickets
        # Right side table - Agent

        # So all the tickets of the customer gets loaded (all the things in left table)
            # and the agents on the side

        from .views import customer
        raised_by = customer.uuid

        try:
            stmt = ibm_db.prepare(conn, fetch_query)
            ibm_db.bind_param(stmt, 1, raised_by)
            ibm_db.execute(stmt)

            tickets = ibm_db.fetch_assoc(stmt)
            tickets_list = []

            if tickets:
                # means, the customer has raised some tickets before
                while tickets != False:
                    temp = []

                    temp.append(tickets['TICKET_ID'])
                    temp.append(str(tickets['RAISED_ON'])[0:10])
                    temp.append(tickets['QUERY_STATUS'])
                    temp.append(tickets['ISSUE'])
                    temp.append(tickets['FIRST_NAME'])

                    tickets_list.append(temp)

                    tickets = ibm_db.fetch_assoc(stmt)

                return render_template(
                    'cust tickets.html',
                    id = 2,
                    tickets_to_show = True,
                    tickets = tickets_list,
                    msg = "These are your tickets"
                )

            else:
                # means, the customer is yet to raise a ticket
                return render_template(
                    'cust tickets.html',
                    id = 2,
                    tickets_to_show = False,
                    msg = "You are yet to rise a ticket"
                )

        except:
            # something fishy happened while loading the customer's tickets
            return render_template(
                'cust tickets.html',
                id = 2,
                to_show = True,
                message = "Something went wrong! Please Try Again"
            )

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))
    
@cust.route('/customer/change', methods = ['GET', 'POST'])
@login_required
def change():
    '''
        Changing the password of the customer
    '''
    from .views import customer
    
    if hasattr(customer, 'first_name'):
        if request.method == 'POST':
            # getting the passwords entered by the customer
            password = request.form.get('password')
            new1 = request.form.get('new-pass-1')
            new2 = request.form.get('new-pass-2')

            msg = ""
            to_show = False

            # validating the passwords entered by the ucer
            if((len(password) or len(new1) or len(new2)) < 8):
                password = new1 = new2 = ""
                msg = "Passwords must be atleast 8 characters long!!" 
                to_show = True     

            elif new1 != new2:
                password = new1 = new2 = ""
                msg = "Passwords do not match" 
                to_show = True

            elif password == new1:
                password = new1 = new2 = ""
                msg = "Old and New passwords cannot be same" 
                to_show = True

            elif (not (re.fullmatch(pass_regex, new1))):
                password = new1 = new2 = ""
                msg = "Enter a valid password"
                to_show = True

            # by here the passwords are evaluated
            if not to_show:
                # updating the password of the customer
                # only if, the existing password of the user is valid
                # checking that if is true the database

                # query tp get the existing encrypted password of the customer
                get_password_sha = '''
                    SELECT passcode FROM customer WHERE cust_id = ?
                '''

                try:
                    stmt = ibm_db.prepare(conn, get_password_sha)
                    ibm_db.bind_param(stmt, 1, customer.uuid)
                    ibm_db.execute(stmt)

                    existing = ibm_db.fetch_assoc(stmt)['PASSCODE']

                    # checking 
                        # if the existing encrypted password is equal to
                        # the encrypted one of the one
                    # that is enetered by the customer
                    
                    # passwords match
                    if (existing == str(hashlib.sha256(password.encode()).hexdigest())):
                        # updating the password of the customer

                        # query to update the password
                        update_password_query = '''
                            UPDATE customer SET passcode = ? WHERE cust_id = ?
                        '''

                        # enrcypting the new password entered by the user
                        enc = str(hashlib.sha256(new1.encode()).hexdigest())

                        change = ibm_db.prepare(conn, update_password_query)
                        ibm_db.bind_param(change, 1, enc)
                        ibm_db.bind_param(change, 2, customer.uuid)

                        ibm_db.execute(change)

                        # password is changed
                        # now logging out the customer and re-directing to login page
                        logout_user()
                        
                        return render_template(
                            'login.html',
                            email = customer.email,
                            password = "",
                            to_show = True, 
                            message = "Password changed! Please login"
                        )
                        
                    else:
                        # passwords do not match
                        to_show = True
                        password = new1 = new2
                        msg = "Invalid current password!"

                except:
                    # something happened while changing the password
                    # alerting the customer
                    to_show = True
                    password = new1 = new2
                    msg = "Password not changed! Please try again"

            return render_template(
                'cust change.html',
                id = 3,
                password = password,
                new1 = new1,
                new2 = new2,
                to_show = to_show,
                message = msg
            )

        return render_template('cust change.html', id = 3)

    else:

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/admin about.html
{% extends 'admin dashboard.html' %}

{% block title %}
    About
{% endblock %}

{% block right %}
<div class="profile-div">
    <h1>About</h1>

    <div class="new-t-div">
        <p>You might as well know all these as an admin</p>

        <div class="about-div">
            <ul>
                <li>Customers create ticket to clarify their queries.</li>
                <li>As an admin, you have to assign those to the agents.</li>
                <li>Agents will have a chat with the customers.</li>
                <li>During the same, agents can answer to the customer.</li>
                <li>Customer closes the ticket once satisfied.</li>
            </ul>

            <a href="{{ url_for('admin.tickets') }}" class="submit-btn new-bol">Unassigned tickets</a>
        </div>
    </div>
</div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/admin support.html
{% extends 'admin dashboard.html' %}

{% block title %}
    Feedbacks
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Feedbacks received!</h1>

        <div class="new-t-div">
            {% if true %}
                <p>{{ msg }}</p>
                <div class="feed-div">
                    {% for feedback in feedbacks %}
                        <div class="feedback-column">
                            <p class="feedback-text">"{{ feedback[3] }}"</p>
                            <p class="feedback-by">By {{ feedback[2] }} ({{ feedback[1] }})</p>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}            
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/agent about.html
{% extends 'agent dashboard.html' %}

{% block title %}
    About
{% endblock %}

{% block right %}
<div class="profile-div">
    <h1>About</h1>

    <div class="new-t-div">
        <p>You might as well know all these as an agent</p>

        <div class="about-div">
            <ul>
                <li>Customers create ticket to clarify their queries.</li>
                <li>Admin assigns some of the tickets to you.</li>
                <li>Once assigned to you, you chat with the customer.</li>
                <li>During the same, you can answer to the customer.</li>
                <li>Customer closes the ticket once satisfied.</li>
            </ul>

            <a href="{{ url_for('agent.assigned') }}" class="submit-btn new-bol">Tickets assigned</a>
        </div>
    </div>
</div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/agent support.html
{% extends 'agent dashboard.html' %}

{% block title %}
    Feedback
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Feedback</h1>

        <div class="new-t-div">
            <p>Your feedback is highly appreciated!</p>
            <form method="POST" action="{{ url_for('agent.support') }}">
                <textarea name="feed-box" class="ticket-area" maxlength="800" placeholder="Your Feedback..."></textarea>
                <p>* Please make sure the feedback is constructive</p>
                <button type="submit" id="new-ticket" class="submit-btn" style="width: 200px;">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/change password.html
{% extends 'base.html' %}

{% block title %}
    Set New Password
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Change Password</h2>
                    <p>Make sure you don't forget</p>
                </div>
                <div class="login-remind">
                    <form action="/forgot/{{role}}/{{email}}/change" method="POST" class="login-form">
                        <label>Password</label>
                        <input type="password" required name="confirm_password" id="password-input" placeholder="Enter your new password"/>
                        
                        <label>Confirm Password</label>
                        <input type="password" required name="password" id="password-input" placeholder="Confirm password"/>
    
                        <div class="show-pass-div">
                            <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                            <p>Show Password</p>
                        </div>
    
                        <button class="submit-btn" type="submit">Change Password</button>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/code.html
{% extends 'base.html' %}

{% block title %}
    Enter the code
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section extra">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Enter the code</h2>
                    <p>Sent to your Registry Account</p>
                </div>
                <div class="login-remind">
                    <form action="/forgot/{{role}}/{{email}}/{{sha}}/" method="POST" class="login-form">
                        <label>Code</label>
                        <input type="text" required name="code-input" placeholder="Enter your code"/>
    
                        <button class="submit-btn" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/cust about.html
{% extends 'cust dashboard.html' %}

{% block title %}
    About
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>About</h1>

        <div class="new-t-div">
            <p>You might as well know all these as a customer</p>

            <div class="about-div">
                <ul>
                    <li>In case you have any doubts, you can create a new ticket.</li>
                    <li>Explain your situation in the ticket legitimately.</li>
                    <li>Admin assigns an agent soon for your ticket.</li>
                    <li>You can chat with the agent to clarify your queries.</li>
                    <li>Close the ticket once you are satisifed.</li>
                </ul>

                <a href="{{ url_for('customer.new') }}" class="submit-btn new-bol">Raise a new ticket</a>
            </div>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/cust profile.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Welcome {{ customer.first_name }}
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Welcome to CCR!</h1>
        <table class="prof-table">
            <tr>
                <th colspan="2" class="prof-table-th">Profile</th>
            </tr>
            <tr>
                <td>First Name</td>
                <td>{{ customer.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>{{ customer.last_name }}</td>
            </tr>
            <tr>
                <td>Role</td>
                <td>Customer</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ customer.email }}</td>
            </tr>
            <tr>
                <td>Date joined</td>
                <td>{{ customer.date }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/cust support.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Support
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Feedback</h1>

        <div class="new-t-div">
            <p>Your feedback is highly appreciated!</p>
            <form method="POST" action="{{ url_for('customer.support') }}">
                <textarea name="feed-box" class="ticket-area" maxlength="50" placeholder="Your Feedback..."></textarea>
                <p>* Please make sure the feedback is constructive</p>
                <button type="submit" id="new-ticket" class="submit-btn" style="width: 200px;">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/forgot.html
{% extends 'base.html' %}

{% block title %}
    Forgot Password?
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section extra">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Forgot Password?</h2>
                    <p>Use your Registry Account</p>
                </div>
                <div class="login-remind">
                    <form action="{{ url_for('blue_print.forgot') }}" method="POST" class="login-form">
                        <label>Email</label>
                        <input type="email" required name="email" placeholder="Enter your email"/>
                        
                        <div class="role-div">
                            <p>Role : </p>
                            <div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                                    <p>Customer</p>
                                </div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                                    <p>Agent</p>
                                </div>
                            </div>
                        </div>
    
                        <button class="submit-btn" type="submit">Get Code</button>
    
                        <div>
                            <a href="{{ url_for('blue_print.login') }}" class="links">Signin instead</a> <br> 
                            <div>
                                <a href="{{ url_for('blue_print.register') }}" class="links">Don't have an account yet? Register</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Sign in</h2>
                    <p>Use your Registry Account</p>
                </div>
                <div class="login-remind">
                    <form action="{{ url_for('blue_print.login') }}" method="POST" class="login-form">
                        <label>Email</label>
                        <input type="email" required value="{{ email }}" name="email" placeholder="Enter your email"/>
                        
                        <label>Password</label>
                        <input type="password" required value="{{ password }}" name="password" id="password-input" placeholder="Enter your password"/>
    
                        <div class="show-pass-div">
                            <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                            <p>Show Password</p>
                        </div>
    
                        <div class="role-div">
                            <p>Role : </p>
                            <div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                                    <p>Customer</p>
                                </div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                                    <p>Agent</p>
                                </div>
                            </div>
                        </div>
    
                        <button class="submit-btn" type="submit">Login</button>
    
                        <div>
                            <!-- {{ url_for('blue_print.forgot') }} -->
                            <a href="{{ url_for('blue_print.forgot') }}" class="links">Forgot Password?</a> <br> 
                            <div>
                                <a href="{{ url_for('blue_print.register') }}" class="links">Don't have an account yet? Register</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block main %}
    <section class="register-section">
        <div class="register-left">
            <h1>Create your Registry Account</h1>

            <form action="{{ url_for('blue_print.register') }}" method="POST">
                <div class="reg-left-input-div">
                    <div>
                        <label>First Name</label>
                        <input required type="text" value="{{ first_name }}" placeholder="First Name" name="first_name" />
                    </div>
                    <div>
                        <label>Last Name</label>
                        <input required type="text" value="{{ last_name }}" placeholder="Last Name" name="last_name" />
                    </div>
                </div>
    
                <div class="email-reg">
                    <label>Email</label>
                    <input required type="email" value="{{ email }}" placeholder="Your email address" name="email" />
                    <p>This will be your Registry account email</p>
                </div>
    
                <div class="role-div">
                    <p>Role : </p>
                    <div>
                        <div style="margin-top: 0px;">
                            <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                            <p>Customer</p>
                        </div>
                        <div style="margin-top: 0px;">
                            <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                            <p>Agent</p>
                        </div>
                    </div>
                </div>
    
                <div class="reg-left-input-div">
                    <div>
                        <label>Password</label>
                        <input required type="password" id="password-input"  value="{{ password }}" placeholder="Password" name="password" />
                    </div>
                    <div>
                        <label>Confirm Password</label>
                        <input required type="password" id="password-input1"  value="{{ confirm_password }}" placeholder="Confirm password" name="confirm_password" />
                    </div>
                </div>
                <p>Use 8 or more characters with a mix of just letters and numbers</p>
    
                <div class="show-pass-div">
                    <input type="checkbox" onclick="showPassword()" name="show password check"/>
                    <p>Show Password</p>
                </div>
    
                <div class="sign-instead-div">
                    <a href="{{ url_for('blue_print.login') }}" class="cust-link">Sign-in instead</a>
                    <button type="submit" class="submit-btn submit-1">Register</button>
                </div>
            </form>
        </div>
        <div class="register-right">
            <img src="{{ url_for('static', filename='images/cart logo white.png') }}" alt="logo"/>
            <h1>Politeness goes far, yet costs nothing</h1>
        </div>
    </section>
{% endblock %}