Project Development Phase/Sprint 3/Customer Care Registry/registry/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for
import hashlib
import re
from flask_login import login_required, login_user, logout_user
import ibm_db
import uuid
from datetime import date
from .model import Customer, Agent, Admin

views = Blueprint("blue_print", __name__)
email_regex = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
pass_regex = r"^[A-Za-z0-9_-]*$"

customer = Customer()
agent = Agent()
admin = Admin()

conn = ibm_db.connect('DATABASE=bludb;HOSTNAME=2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud;PORT=30756;SECURITY=SSL;SSLServerCertificate=DigiCertGlobalRootCA.crt;UID=tdn81266;PWD=7LY8okjAouJf3LoO', '', '')

@views.route('/logout')
@login_required
def logout():
    session.pop('LOGGED_IN_AS')
    logout_user()

    return redirect(url_for('blue_print.login'))

@views.route('/', methods = ['GET', 'POST'])
@views.route('/login', methods = ['GET', 'POST'])
def login():
    # if method is POST
    if request.method == 'POST':
        # getting the data entered by the user 
        email = request.form.get('email')
        password = request.form.get('password')
        role = request.form.get('role-check')

        msg = ""
        to_show = False

        # validating the inputs entered by the user
        if(not (re.fullmatch(email_regex, email))):
            msg = "Enter a valid email"
            to_show = True

        elif (len(password) < 8):
            msg = "Password must be atleast 8 characters long!"
            to_show = True

        # Admin login
        if email == "admin.ccr@gmail.com":
            if password == "admin.ccr@2022":
                # initialising admin object
                admin.set(email, password)

                session.permanent = False
                session['LOGGED_IN_AS'] = "ADMIN"                            
                login_user(admin, remember=True)
                
                return redirect(url_for('admin.tickets'))

            else:
                to_show = True
                password = ""
                msg = "Invalid password!"

        # Customer or Agent
        else:
            if to_show:
                # there is something fishy with the user's inputs
                password = ""

            elif (not to_show):
                # the user's inputs are valid
                # checking if the login credentials are valid
                if role == "Customer":
                    # checking if the entry of the mail entered is present in the database
                    mail_check_query = "SELECT * FROM customer WHERE email = ?"
                    stmt = ibm_db.prepare(conn, mail_check_query)
                    ibm_db.bind_param(stmt, 1, email)
                    ibm_db.execute(stmt)

                    account = ibm_db.fetch_assoc(stmt)

                    if account:
                        # valid customer
                        # i.e, mail is present in the database

                        # checking if the customer entered a valid password now
                        # encrypting the entered password
                        passcode = str(hashlib.sha256(password.encode()).hexdigest())

                        # now checking if the encrypted string is same as that of the one in database
                        if (account['PASSCODE'] == passcode):
                            msg = "Valid Login"
                            to_show = True

                            # creating a customer object
                            customer.set(
                                account['CUST_ID'],
                                account['FIRST_NAME'],
                                account['LAST_NAME'],
                                account['EMAIL'],
                                account['PASSCODE'],
                                account['DATE_JOINED']
                            )

                            session.permanent = False
                            session['LOGGED_IN_AS'] = "CUSTOMER"
                            login_user(customer, remember=True)

                            return redirect(url_for('customer.profile'))

                        else:
                            # customer entered invalid password
                            msg = "Invalid password"
                            password = ""
                            to_show = True

                    else:
                        # invalid customer
                        # i.e, entered mail is not present in the database
                        msg = "User does not exist"
                        email = ""
                        password = ""
                        to_show = True

                else:
                    # user is an Agent
                    # checking if the entry of the mail entered is present in the agent's table
                    mail_check_query = "SELECT * FROM agent WHERE email = ?"
                    stmt = ibm_db.prepare(conn, mail_check_query)
                    ibm_db.bind_param(stmt, 1, email)
                    ibm_db.execute(stmt)

                    account = ibm_db.fetch_assoc(stmt)

                    if account:
                        # the mail entered by the agent is in the database

                        # checking if the customer entered a valid password now
                        # encrypting the entered password
                        passcode = str(hashlib.sha256(password.encode()).hexdigest())

                        # now checking if this passcode is equal to that of the password in database
                        if(account['PASSCODE'] == passcode):
                            # valid password
                            msg = "Valid Login"
                            to_show = True

                            # initialising the agent object
                            agent.set(
                                account['AGENT_ID'],
                                account['FIRST_NAME'],
                                account['LAST_NAME'],
                                account['EMAIL'],
                                account['PASSCODE'],
                                account['DATE_JOINED'],
                                account['CONFIRMED']
                            )

                            session.permanent = False
                            session['LOGGED_IN_AS'] = "AGENT"
                            login_user(agent, remember=True)

                            if agent.confirm:
                                # the agent is confirmed by the admin
                                # so, re-directing the agent to his/her profile page
                                return redirect(url_for('agent.profile'))

                            else:
                                # the agent is not yet verified by the admin
                                # re-directing the agent to the agent no show page
                                return redirect(url_for('agent.no_show'))

                        else:
                            # invalid password
                            msg = "Invalid password"
                            password = ""
                            to_show = True

                    else:
                        # invalid agent 
                        # i.e, entered mail is not present in the database
                        msg = "Agent does not exist"
                        email = ""
                        password = ""
                        to_show = True

        return render_template(
            'login.html',
            to_show = to_show,
            message = msg,
            email = email,
            password = password
        )

    return render_template('login.html')

@views.route('/register', methods = ['GET', 'POST'])
def register():
    # if method is POST
    if request.method == 'POST':
        # getting all the data entered by the user
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        role = request.form.get('role-check')

        msg = ""
        to_show = False

        # validating the inputs 
        if len(first_name) < 3:
            msg = "First Name must be atleast 3 characters long!"
            to_show = True

        elif len(last_name) < 1:
            msg = "Last Name must be atleast 1 characters long!"
            to_show = True

        elif(not (re.fullmatch(email_regex, email))):
            msg = "Please enter valid email"
            to_show = True

        elif((len(password) < 8) or (len(confirm_password) < 8)):
            msg = "Password must be atleast 8 characters long!"
            to_show = True

        elif (password != confirm_password):
            msg = "Passwords do not match"
            to_show = True

        elif (not (re.fullmatch(pass_regex, password))):
            msg = "Enter valid password"
            to_show = True

        if to_show:
            # there is something fishy with the inputs
            password = confirm_password = ""

        # by here the inputs are validated, because to_show is False
        # registering the user / agent with the database
        elif (not to_show):
            if role == "Customer":
                # the user is a Customer
                # checking whether the user with the same email already there
                check_mail_query = "SELECT * FROM customer WHERE email = ?"
                stmt = ibm_db.prepare(conn, check_mail_query)
                ibm_db.bind_param(stmt, 1, email)
                ibm_db.execute(stmt)

                account = ibm_db.fetch_assoc(stmt)

                if account:
                    # user already exists
                    msg = "Email already exists!"
                    email = ""

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/address.html
{% extends 'base.html' %}

{% block title %}
    Address Column
{% endblock %}

{% block main %}
    <div class="dashboard-div">
        <nav>
            <div class="dash-nav">
                <div>
                    <div class="dash-img-text">
                        {% if user == "AGENT" %}
                            <a href="{{ url_for('agent.assigned') }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                            <img src="{{ url_for('static', filename='images/cust profile.png') }}" class="img-in-nav" alt="logo"/>
                        {% else %}
                            <a href="{{ url_for('customer.tickets') }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                            <img src="{{ url_for('static', filename='images/agent.png') }}" class="img-in-nav" alt="logo"/>
                        {% endif %}
                        <h3>{{ name }}</h3>
                    </div>
                </div>
                <div>
                    <div style="align-items: center;">
                        {% if value == "True" %}
                            {% if user == "CUSTOMER" %}
                                <a href="/customer/close/{{ id }}"><button class="logout-btn">CLOSE TICKET</button></a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <div class="chat-body">
            <div class="chat-contents" id="content">
                {% if msgs_to_show %}
                    {% for chat in chats %}
                        {% if chat['SENDER_ID'] == sender_id %}
                            <div class="message-sent">{{ chat['MESSAGE'] }}</div>
                        {% else %}
                            <div class="message-sent received">{{ chat['MESSAGE'] }}</div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
            <div class="chat-input-div">
                {% if value == "True" %}
                    <form method="POST" action="{{ post_url }}">
                        <input name="message-box" class="chat-input" type="text" placeholder="Type something" required/>
                        <button type="submit" class="chat-send">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                        </button>
                    </form>
                {% else %}
                    <div>
                        {% if user == "CUSTOMER" %}
                            <h4>You closed this ticket. Chats are disabled</h4>
                        {% else %}
                            <h4>{{ name }} closed this ticket. Chats are disabled</h4>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/admin about.html
{% extends 'admin dashboard.html' %}

{% block title %}
    About
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/admin acc agent.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All Requests
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Pending Requests</h1>
        <div class="new-t-div">
            {% if agents_to_show %}
                <p>{{ msg }}</p>
                
                <table class="agents-table">
                    <tr>
                        <th class="agents-table-heading">AGENT ID</th>
                        <th class="agents-table-heading">EMAIL</th>
                        <th class="agents-table-heading">FIRST NAME</th>
                        <th class="agents-table-heading">JOINED <br/> DATE</th>
                        <th class="agents-table-heading">ACCEPT?</th>
                    </tr>
                    {% for agent in agents %}
                        <tr>
                            <td class="agents-table-element">{{ agent[0][0:5] }}</td>
                            <td class="agents-table-element">{{ agent[1] }}</td>
                            <td class="agents-table-element">{{ agent[2] }}</td>
                            <td class="agents-table-element">{{ agent[3] }}</td>
                            <td class="agents-table-element">
                                <div class="accept-close-div">
                                    <div><i onclick="agree('{{ agent[1] }}')" class="fa fa-check agree" aria-hidden="true"></i></div>
                                    <div><i onclick="deny('{{ agent[1] }}')" class="fa fa-times deny" aria-hidden="true"></i></div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>

    <script>
        function agree(email){
            var decision = confirm("Do you want to accept the agent?")

            if (decision){
                url = '/admin/' + email + '/True'

                fetch(url, {

                }).then((_res) => {
                    window.location.href = "/admin/accept"
                })
            }
        }

        function deny(email){
            var decision = confirm('If you do not accept the agent, the agent will be deleted from the databse. Is it ok?')
        
            if(decision){
                url = '/admin/' + email + '/False'

                fetch(url, {

                }).then((_res) => {
                    window.location.href = "/admin/accept"
                    console.log("Agent deleted")
                })
            }
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/admin agents.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All Agents
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>All Agents</h1>

        <div class="new-t-div">
            {% if agents_to_show %}
                <p>{{ msg }}</p>
                <table class="agents-table">
                    <tr>
                        <th class="agents-table-heading">AGENT ID</th>
                        <th class="agents-table-heading">JOINED DATE</th>
                        <th class="agents-table-heading">FIRST NAME</th>
                        <th class="agents-table-heading">LAST NAME</th>
                        <th class="agents-table-heading">EMAIL</th>
                    </tr>
                    {% for agent in agents %}
                        <tr>
                            <td class="agents-table-element">{{ agent[0][0:5] }}</td>
                            <td class="agents-table-element">{{ agent[1] }}</td>
                            <td class="agents-table-element">{{ agent[2] }}</td>
                            <td class="agents-table-element">{{ agent[3] }}</td>
                            <td class="agents-table-element">{{ agent[4] }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/agent dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div">
        <ul  id="dash-parent-list">
            <li>
                <a href="{{ url_for('agent.profile') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h3>Profile</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('agent.assigned') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h3>Tickets Assigned</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('agent.change') }}">
                    <div class="link-items">
                        <div><i class="fa fa-key" aria-hidden="true"></i></div>
                        <h3>Change Password</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('agent.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h3>About</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('agent.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h3>Feedback</h3>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/agent no show.html
{% extends 'base.html' %}

{% block title %}
    Welcome {{ agent.first_name }}!
{% endblock %}

{% block main %}
    <div class="agent-no-show">
        <form method="GET" action="{{ url_for('blue_print.logout') }}">
            <img class="no-show-img" src="../static/images/cart logo white-modified.png" alt="logo"/>
            <h2 class="no-show-header">Welcome agent, {{ agent.first_name }}</h2>
            <p>It seems your account is not yet verified by the admin! So would you please login after a while.</p>
            <button class="logout-btn" type="submit">LOGOUT</button>
        </form>
    </div>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/agent profile.html
{% extends 'agent dashboard.html' %}

{% block title %}
    Welcome {{ agent.first_name }}!
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Welcome to CCR!</h1>
        <table class="prof-table">
            <tr>
                <th colspan="2" class="prof-table-th">Profile</th>
            </tr>
            <tr>
                <td>First Name</td>
                <td>{{ agent.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>{{ agent.last_name }}</td>
            </tr>
            <tr>
                <td>Role</td>
                <td>Agent</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ agent.email }}</td>
            </tr>
            <tr>
                <td>Date joined</td>
                <td>{{ agent.date }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/agent support.html
{% extends 'agent dashboard.html' %}

{% block title %}
    Feedback
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image" href="{{ url_for('static', filename='images/cart logo white-modified.png') }}">
    
    <!-- Linking css, js, Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/pass.js') }}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Linking Watson Assistant -->
    {% block watson %}
    {% endblock %}
</head>
<body>
    {% block alert %}
        {% if to_show %}
            <script>
                alert('{{ message }}')
            </script>
        {% endif %}
    {% endblock %}

    {% block main %}
    {% endblock %}
</body>
</html>

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/cust dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div">
        <ul  id="dash-parent-list">
            <li>
                <a href="{{ url_for('customer.profile') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h3>Profile</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.new') }}">
                    <div class="link-items">
                        <div><i class="fa fa-plus" aria-hidden="true"></i></div>
                        <h3>New ticket</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.tickets') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h3>Tickets</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.change') }}">
                    <div class="link-items">
                        <div><i class="fa fa-key" aria-hidden="true"></i></div>
                        <h3>Change Password</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h3>About</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h3>Feedback</h3>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
            console.log("function called")
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/cust profile.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Welcome {{ customer.first_name }}
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Welcome to CCR!</h1>
        <table class="prof-table">
            <tr>
                <td>First Name</td>
                <td>{{ customer.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>{{ customer.last_name }}</td>
            </tr>
            <tr>
                <td>Role</td>
                <td>Customer</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ customer.email }}</td>
            </tr>
            <tr>
                <td>Date joined</td>
                <td>{{ customer.date }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/cust support.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Support
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Feedback</h1>

        <div class="new-t-div">
            <p>Your feedback is highly appreciated!</p>
            <form method="POST" action="{{ url_for('customer.support') }}">
                <textarea name="feed-box" class="ticket-area" maxlength="800" placeholder="Your Feedback..."></textarea>
                <p>* Please make sure the feedback is constructive</p>
                <button type="submit" id="new-ticket" class="submit-btn" style="width: 200px;">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/dashboard.html
{% extends 'base.html' %}

{% block main %}
    <div class="dashboard-div">
        <nav>
            <div class="dash-nav">
                <div>
                    <div class="dash-img-text">
                        <img src="../static/images/cart logo white-modified.png" class="img-in-nav" alt="logo"/>
                        <h3>Customer Care Registry</h3>
                    </div>
                </div>
                <div>
                    <div class="online-div" onclick="showSettings()">
                        {% if user == "AGENT" %}
                            <img src="../static/images/agent.png" class="img-in-nav" alt="logo"/>
                        {% elif user == "ADMIN" %}
                            <img src="../static/images/admin.png" class="img-in-nav" alt="logo"/>
                        {% else %}
                            <img src="../static/images/cust profile.png" class="img-in-nav" alt="logo"/>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        
        <div class="dash-body">
            <div class="dash-left">
                {% block left %}
                {% endblock %}
            </div>
            <div class="dash-right">
                {% block right %}
                {% endblock %}
            </div>
        </div>

        <div class="settings-menu" id="settings-menu" style="visibility: hidden;">
            <div>
                <p>Want to Logout?</p>
                <a href="{{ url_for('blue_print.logout') }}">
                    <button class="logout-btn" type="button">Logout</button>
                </a>
            </div>
        </div>
    </div>

    <script>
        function showSettings(){
            var settings = document.getElementById("settings-menu");

            settings.style.visibility = settings.style.visibility == "hidden" ? "visible" : "hidden";
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 3/Customer Care Registry/registry/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Sign in</h2>
                    <p>Use your Registry Account</p>
                </div>
                <div class="login-remind">
                    <form action="{{ url_for('blue_print.login') }}" method="POST" class="login-form">
                        <label>Email</label>
                        <input type="email" required value="{{ email }}" name="email" placeholder="Enter your email"/>
                        
                        <label>Password</label>
                        <input type="password" required value="{{ password }}" name="password" id="password-input" placeholder="Enter your password"/>
    
                        <div class="show-pass-div">
                            <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                            <p>Show Password</p>
                        </div>
    
                        <div class="role-div">
                            <p>Role : </p>
                            <div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                                    <p>Customer</p>
                                </div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                                    <p>Agent</p>
                                </div>
                            </div>
                        </div>
    
                        <button class="submit-btn" type="submit">Login</button>
    
                        <div>
                            <a href="#" class="links">Forgot Password?</a> <br> 
                            <div>
                                <a href="{{ url_for('blue_print.register') }}" class="links">Don't have an account yet? Register</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}